ALTER TABLE photos ADD COLUMN IF NOT EXISTS taken_at DATE;
ALTER TABLE photos ADD COLUMN IF NOT EXISTS exposure_time TEXT;
ALTER TABLE photos ADD COLUMN IF NOT EXISTS focal_length NUMERIC(8,2);
ALTER TABLE photos ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7);
ALTER TABLE photos ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7);
ALTER TABLE photos ADD COLUMN IF NOT EXISTS nextcloud_url TEXT;
